export type ConfigurableFormKey = 'patient' | 'hts' | 'pep' | 'prep' | 'art';

export interface DefaultFieldDef {
  label: string;
  required?: boolean;
  visible?: boolean;
}

export interface DefaultSchema {
  fields: Record<string, DefaultFieldDef>;
  options?: Record<string, string[]>;
}

export const FORM_SCHEMAS: Record<ConfigurableFormKey, DefaultSchema> = {
  patient: {
    fields: {
      first_name: { label: 'First Name', required: true, visible: true },
      middle_name: { label: 'Middle Name', visible: true },
      last_name: { label: 'Last Name', required: true, visible: true },
      preferred_name: { label: 'Preferred Name', visible: true },
      sex: { label: 'Sex', required: true, visible: true },
      gender: { label: 'Gender Identity', visible: true },
      date_of_birth: { label: 'Date of Birth', required: true, visible: true },
      current_clinic_id: { label: 'Current Clinic', required: true, visible: true },
      marital_status: { label: 'Marital Status', visible: true },
      phone: { label: 'Phone Number', visible: true },
      email: { label: 'Email Address', visible: true },
      address: { label: 'Address', visible: true },
      state_id: { label: 'State', visible: true },
      lga_id: { label: 'LGA', visible: true },
      city: { label: 'City', visible: true },
      educational_level: { label: 'Educational Level', visible: true },
      occupation: { label: 'Occupation', visible: true },
      occupation_specify: { label: 'Specify Occupation', visible: true },
      emergency_contact_name: { label: 'Emergency Contact Name', visible: true },
      emergency_contact_relationship: { label: 'Emergency Contact Relationship', visible: true },
      emergency_contact_phone: { label: 'Emergency Contact Phone', visible: true },
    },
    options: {
      sex: ['Male', 'Female', 'Intersex'],
      marital_status: ['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Cohabiting'],
      educational_level: ['None', 'Primary', 'Secondary', 'Tertiary', 'Vocational', 'Postgraduate'],
      occupation: [
        'Student',
        'Employed',
        'Self-employed',
        'Unemployed',
        'Retired',
        'Farmer',
        'Trader',
        'Artisan',
        'Civil Servant',
        'Health Worker',
        'Transport Worker',
        'Sex Worker',
        'Other',
      ],
    },
  },
  hts: {
    fields: {
      // Initial
      date_of_visit: { label: 'Date of Visit', required: true, visible: true },
      client_code: { label: 'Client Code', required: true, visible: true },
      target_group_code: { label: 'Target Group', required: true, visible: true },
      marital_status: { label: 'Marital Status', required: true, visible: true },
      type_of_hts: { label: 'Type of HTS', required: true, visible: true },
      settings: { label: 'Setting', required: true, visible: true },
      testing_modality: { label: 'Testing Modality', required: true, visible: true },
      type_of_session: { label: 'Session Type', required: true, visible: true },
      num_children_under_15: { label: 'Number of Children Under 15', required: true, visible: true },
      source_of_referral: { label: 'Source of Referral', required: true, visible: true },
      sex_partners: { label: 'Sex Partners', required: true, visible: true },
      educational_level: { label: 'Educational Level', required: true, visible: true },
      occupation: { label: 'Occupation', required: true, visible: true },
      first_time_visit: { label: 'First Time Visit', visible: true },
      // Pre-test (knowledge/risk/partner/STI/GBV)
      previously_tested_negative: { label: 'Previously Tested Negative', visible: true },
      informed_hiv_transmission: { label: 'Informed About HIV Transmission', visible: true },
      informed_risk_factors: { label: 'Informed About Risk Factors', visible: true },
      informed_prevention_methods: { label: 'Informed About Prevention Methods', visible: true },
      informed_test_results: { label: 'Informed About Test Results', visible: true },
      consent_given: { label: 'Consent Given', visible: true },
      used_drugs_sexual_performance: { label: 'Used Drugs For Sexual Performance', visible: true },
      transmission_sexual_intercourse: { label: 'Transmission: Sexual Intercourse', visible: true },
      transmission_blood_transfusion: { label: 'Transmission: Blood Transfusion', visible: true },
      transmission_mother_to_child: { label: 'Transmission: Mother To Child', visible: true },
      transmission_sharing_toilet: { label: 'Transmission: Sharing Toilet', visible: true },
      transmission_sharp_objects: { label: 'Transmission: Sharing Sharp Objects', visible: true },
      transmission_eating_utensils: { label: 'Transmission: Sharing Eating Utensils', visible: true },
      transmission_mosquito_bites: { label: 'Transmission: Mosquito Bites', visible: true },
      transmission_kissing: { label: 'Transmission: Kissing', visible: true },
      transmission_hugging: { label: 'Transmission: Hugging', visible: true },
      prevention_faithful_partner: { label: 'Prevention: Faithful Partner', visible: true },
      prevention_condom_use: { label: 'Prevention: Condom Use', visible: true },
      prevention_abstinence: { label: 'Prevention: Abstinence', visible: true },
      prevention_delay_sexual_debut: { label: 'Prevention: Delay Sexual Debut', visible: true },
      prevention_reduce_partners: { label: 'Prevention: Reduce Partners', visible: true },
      prevention_avoid_risky_partners: { label: 'Prevention: Avoid Risky Partners', visible: true },
      prevention_avoid_sharp_objects: { label: 'Prevention: Avoid Sharing Sharp Objects', visible: true },
      prevention_healthy_looking_can_have_hiv: { label: 'Prevention: Healthy Looking Can Have HIV', visible: true },
      risk_blood_transfusion: { label: 'Risk: Blood Transfusion', visible: true },
      risk_unprotected_vaginal_sex: { label: 'Risk: Unprotected Vaginal Sex', visible: true },
      risk_unprotected_anal_sex: { label: 'Risk: Unprotected Anal Sex', visible: true },
      risk_sharing_needles: { label: 'Risk: Sharing Needles', visible: true },
      risk_sti: { label: 'Risk: STI', visible: true },
      risk_multiple_partners: { label: 'Risk: Multiple Partners', visible: true },
      risk_sex_under_influence: { label: 'Risk: Sex Under Influence', visible: true },
      risk_anal_sex: { label: 'Risk: Anal Sex', visible: true },
      risk_vaginal_sex: { label: 'Risk: Vaginal Sex', visible: true },
      risk_paid_for_sex: { label: 'Risk: Paid For Sex', visible: true },
      risk_been_paid_for_sex: { label: 'Risk: Been Paid For Sex', visible: true },
      risk_condom_breakage: { label: 'Risk: Condom Breakage', visible: true },
      risk_sexual_orgy: { label: 'Risk: Sexual Orgy', visible: true },
      partner_newly_diagnosed_on_treatment: { label: 'Partner Newly Diagnosed On Treatment', visible: true },
      partner_on_arv_suppressed_vl: { label: 'Partner On ARV Suppressed VL', visible: true },
      partner_pregnant_on_arv: { label: 'Partner Pregnant On ARV', visible: true },
      partner_returned_after_ltfu: { label: 'Partner Returned After LTFU', visible: true },
      partner_adolescent_hiv_positive: { label: 'Partner Adolescent HIV Positive', visible: true },
      partner_hiv_positive: { label: 'Partner HIV Positive', visible: true },
      partner_injects_drugs: { label: 'Partner Injects Drugs', visible: true },
      partner_has_sex_with_men: { label: 'Partner Has Sex With Men', visible: true },
      partner_transgender: { label: 'Partner Transgender', visible: true },
      sti_urethral_discharge: { label: 'STI: Urethral Discharge', visible: true },
      sti_scrotal_swelling: { label: 'STI: Scrotal Swelling', visible: true },
      sti_genital_sore: { label: 'STI: Genital Sore', visible: true },
      sti_anal_pain: { label: 'STI: Anal Pain', visible: true },
      sti_anal_discharge: { label: 'STI: Anal Discharge', visible: true },
      sti_anal_itching: { label: 'STI: Anal Itching', visible: true },
      experiencing_violence: { label: 'Experiencing Violence', visible: true },
      // Testing
      screening_test_result: { label: 'Screening Test Result', required: true, visible: true },
      screening_test_date: { label: 'Screening Test Date', required: true, visible: true },
      confirmatory_test_result: { label: 'Confirmatory Test Result', visible: true },
      confirmatory_test_date: { label: 'Confirmatory Test Date', visible: true },
      final_result: { label: 'Final HIV Test Result', required: true, visible: true },
      // Post-test
      previous_hiv_test_status: { label: 'Previous HIV Test Status', required: true, visible: true },
      result_form_signed: { label: 'Result Form Signed', visible: true },
      result_form_filled: { label: 'Result Form Filled', visible: true },
      client_received_result: { label: 'Client Received Result', visible: true },
      partner_uses_fp_method: { label: 'Partner Uses Family Planning', visible: true },
      partner_uses_condom: { label: 'Partner Uses Condom', visible: true },
      post_test_counseling_done: { label: 'Post-Test Counseling Done', visible: true },
      client_referred_to_services: { label: 'Client Referred To Services', visible: true },
      risk_reduction_plan_developed: { label: 'Risk Reduction Plan Developed', visible: true },
      disclosure_plan_developed: { label: 'Disclosure Plan Developed', visible: true },
      will_bring_partners: { label: 'Will Bring Partners', visible: true },
      will_bring_children: { label: 'Will Bring Children', visible: true },
      provided_fp_info: { label: 'Family Planning Info Provided', visible: true },
      condom_use_demonstrated: { label: 'Condom Use Demonstrated', visible: true },
      condoms_provided: { label: 'Condoms Provided', visible: true },
      comments: { label: 'Comments', visible: true },
      // Referral
      referring_org_unit: { label: 'Referring Unit', visible: true },
      referring_org_name: { label: 'Referring Organization Name', visible: true },
      referring_org_address: { label: 'Referring Organization Address', visible: true },
      referring_org_phone: { label: 'Referring Organization Phone', visible: true },
      referring_org_contact_person: { label: 'Referring Contact Person', visible: true },
      referred_org_unit: { label: 'Referred Unit', visible: true },
      referred_org_name: { label: 'Referred Organization Name', visible: true },
      referred_org_address: { label: 'Referred Organization Address', visible: true },
      referred_org_phone: { label: 'Referred Organization Phone', visible: true },
      referred_org_contact_person: { label: 'Referred Contact Person', visible: true },
      referral_services: { label: 'Referral Services', visible: true },
    },
    options: {
      target_group_code: ['MSM', 'FSW', 'PWID', 'TG', 'General Population', 'Other'],
      marital_status: ['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Cohabiting'],
      type_of_hts: ['PITC', 'Voluntary'],
      settings: ['CT', 'FP', 'OPD', 'OTHERS', 'OUTREACH', 'STI', 'STANDALONE HTS', 'TB', 'WARD'],
      testing_modality: [
        'ANC 1',
        'ACUTE CARE',
        'COMMUNITY TESTING/OUTREACH',
        'OPD',
        'OTHER PITC',
        'STI',
        'VCT',
        'TESTING THROUGH SOCIAL MEDIA',
      ],
      type_of_session: ['Couple', 'Individual', 'Previously tested'],
      source_of_referral: ['Friend', 'KOL', 'Other', 'Social Media', 'Self'],
      sex_partners: ['Male', 'Female', 'Both'],
      educational_level: ['None', 'Primary', 'Secondary', 'Tertiary', 'Vocational', 'Postgraduate'],
      occupation: [
        'Student',
        'Employed',
        'Self-employed',
        'Unemployed',
        'Retired',
        'Farmer',
        'Trader',
        'Artisan',
        'Civil Servant',
        'Health Worker',
        'Transport Worker',
        'Sex Worker',
        'Other',
      ],
      test_results: ['Non-reactive', 'Not done', 'Reactive'],
      previous_hiv_test_status: [
        'Not previously tested',
        'Previously tested negative',
        'Previously tested positive in HIV care',
        'Previously tested positive not in HIV care',
      ],
      referral_services: [
        'ART Treatment',
        'PrEP Services',
        'TB Screening',
        'STI Treatment',
        'Family Planning',
        'Psychosocial Support',
        'Nutrition Services',
        'PMTCT Services',
        'Other Medical Services',
      ],
    },
  },
  pep: {
    fields: {
      mode_of_exposure: { label: 'Mode of Exposure', required: true, visible: true },
      duration_before_pep: { label: 'Duration Before PEP', required: true, visible: true },
      pep_supporter: { label: 'Supporter Name', required: true, visible: true },
      supporter_relationship: { label: 'Relationship', required: true, visible: true },
      supporter_telephone: { label: 'Phone Number', required: true, visible: true },
    },
    options: {
      mode_of_exposure: ['Non-occupational', 'Occupational'],
      duration_before_pep: ['<24hrs', '<48hrs', '<72hrs', '>72hrs'],
      supporter_relationship: ['Caregiver', 'Child', 'Father', 'Mother', 'Sibling', 'Guardian', 'Other'],
    },
  },
  prep: {
    fields: {
      date_initial_adherence_counseling: {
        label: 'Date of Initial Adherence Counseling',
        required: true,
        visible: true,
      },
      date_prep_initiated: { label: 'Date PrEP Initiated', visible: true },
      prep_type_at_start: { label: 'PrEP Type at Start', visible: true },
      history_of_drug_allergies: { label: 'History of Drug Allergies', visible: true },
      allergy_details: { label: 'Allergy Details', visible: true },
      transferred_in: { label: 'Transferred In', visible: true },
      previous_enrollment_id: { label: 'Previous Enrollment ID', visible: true },
      transferred_from_facility: { label: 'Transferred From Facility', visible: true },
    },
    options: {
      prep_type_at_start: ['ED PrEP', 'Injectable / CAB-LA', 'ORAL', 'RING'],
    },
  },
  art: {
    fields: {
      art_no: { label: 'ART Number', required: true, visible: true },
      date_confirmed_hiv_positive: { label: 'Date Confirmed HIV Positive', required: true, visible: true },
      date_enrolled_into_hiv_care: { label: 'Date Enrolled into HIV Care', required: true, visible: true },
      mode_of_hiv_test: { label: 'Mode of HIV Test', visible: true },
      entry_point: { label: 'Entry Point', required: true, visible: true },
      where_test_was_done: { label: 'Where Test Was Done', visible: true },
      prior_art: { label: 'Prior ART', visible: true },
      name_of_next_of_kin: { label: 'Name of Next of Kin', visible: true },
      relationship_with_next_of_kin: { label: 'Relationship with Next of Kin', visible: true },
      phone_no_of_next_of_kin: { label: 'Next of Kin Phone Number', visible: true },
    },
    options: {
      mode_of_hiv_test: ['HIV-AB', 'PCR'],
      entry_point: [
        'VCT',
        'ANC/PMTCT',
        'Index testing',
        'Inpatient',
        'OPD',
        'Outreach',
        'STI clinic',
        'TB-DOT',
        'Transferred in',
        'Others',
      ],
      prior_art: [
        'PEP',
        'PMTCT only',
        'Transfer in with records',
        'Transfer in without records',
      ],
    },
  },
};
